name: Daily Price Tracker

# Run every day at 08:00 UTC
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:  # allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Save Google creds
      - name: Save Google creds
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDS }}
        run: |
          echo "$GCP_CREDS" > price-tracker-credentials.json

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run the scraper
      - name: Run scraper
        run: |
          python price_tracker.py
